name: Delete Deployments
on: workflow_dispatch # გაშვება მოხდება ხელით

jobs:
  delete-deployments:
    runs-on: ubuntu-latest
    steps:
      - name: Delete all deployments
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: Production
          onlyRemoveDeployments: true
